### ISSUE TITLE
TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.

### ISSUE THREAD

**Issue by andrius** [worldveil/dejavu#115]
Dockerized dejavu (https://github.com/andrius/dejavu-docker), but getting following error

```
Failed fingerprinting
Traceback (most recent call last):
  File "/dejavu/dejavu/__init__.py", line 77, in fingerprint_directory
    song_name, hashes, file_hash = iterator.next()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 668, in next
    raise value
TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.```

Shall I use some old numpy version to get stuff working?

**Comment by andrius** [comment]
Fixed now, you could investigate my Dockerfile too :) No issues, please close!

**Comment by adong77** [comment]
Try with old numpy version:
```
$sudo pip install numpy==1.10.0.
```
