### ISSUE TITLE
djv.fingerprint_directory Failed fingerprinting error

### ISSUE THREAD

**Issue by rshahamiri** [worldveil/dejavu#150]
Hi guys,
I'm getting the following errors. Running MAC OS and Python 2.7, I tried reinstalling ffmpeg using _brew install ffmpeg_, and tried different versions of numpy but with no lock. Appreciate your help:

_djv.fingerprint_directory("./audio_files", [".wav"],3)
Fingerprinting channel 1/1 for ./audio_files/0126.wav
Fingerprinting channel 1/1 for ./audio_files/0116.wav
Fingerprinting channel 1/1 for ./audio_files/0132.wav
Fingerprinting channel 1/1 for ./audio_files/0130.wav
Failed fingerprinting
Traceback (most recent call last):
  File "dejavu/__init__.py", line 77, in fingerprint_directory
    song_name, hashes, file_hash = iterator.next()
  File "/anaconda3/envs/python27env/lib/python2.7/multiprocessing/pool.py", line 673, in next
    raise value
TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.
Failed fingerprinting
Traceback (most recent call last):
  File "dejavu/__init__.py", line 77, in fingerprint_directory
    song_name, hashes, file_hash = iterator.next()
  File "/anaconda3/envs/python27env/lib/python2.7/multiprocessing/pool.py", line 673, in next
    raise value
TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.
Failed fingerprinting
Traceback (most recent call last):
  File "dejavu/__init__.py", line 77, in fingerprint_directory
    song_name, hashes, file_hash = iterator.next()
  File "/anaconda3/envs/python27env/lib/python2.7/multiprocessing/pool.py", line 673, in next
    raise value
TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.
Failed fingerprinting
Traceback (most recent call last):
  File "dejavu/__init__.py", line 77, in fingerprint_directory
    song_name, hashes, file_hash = iterator.next()
  File "/anaconda3/envs/python27env/lib/python2.7/multiprocessing/pool.py", line 673, in next
    raise value
TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead._

**Comment by kono0514** [comment]
#143

**Comment by grishabh282** [comment]
can you give me dejavu fingerprint github link

**Comment by grishabh282** [comment]
Failed fingerprinting
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "c:\users\rishabh\appdata\local\programs\python\python37\Lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Rishabh\Desktop\audio\dejavu\dejavu\__init__.py", line 180, in _fingerprint_worker
    channels, Fs, file_hash = decoder.read(filename, limit)
  File "C:\Users\Rishabh\Desktop\audio\dejavu\dejavu\decoder.py", line 51, in read
    audiofile = AudioSegment.from_file(filename)
  File "C:\Users\Rishabh\Desktop\audio\venv\lib\site-packages\pydub\audio_segment.py", line 665, in from_file
    info = mediainfo_json(orig_file)
  File "C:\Users\Rishabh\Desktop\audio\venv\lib\site-packages\pydub\utils.py", line 263, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
  File "c:\users\rishabh\appdata\local\programs\python\python37\Lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "c:\users\rishabh\appdata\local\programs\python\python37\Lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Rishabh\Desktop\audio\dejavu\dejavu\__init__.py", line 77, in fingerprint_directory
    song_name, hashes, file_hash = iterator.next()
  File "c:\users\rishabh\appdata\local\programs\python\python37\Lib\multiprocessing\pool.py", line 748, in next
    raise value
FileNotFoundError: [WinError 2] The system cannot find the file specified
Failed fingerprinting
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "c:\users\rishabh\appdata\local\programs\python\python37\Lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Rishabh\Desktop\audio\dejavu\dejavu\__init__.py", line 180, in _fingerprint_worker
    channels, Fs, file_hash = decoder.read(filename, limit)
  File "C:\Users\Rishabh\Desktop\audio\dejavu\dejavu\decoder.py", line 51, in read
    audiofile = AudioSegment.from_file(filename)
  File "C:\Users\Rishabh\Desktop\audio\venv\lib\site-packages\pydub\audio_segment.py", line 665, in from_file
    info = mediainfo_json(orig_file)
  File "C:\Users\Rishabh\Desktop\audio\venv\lib\site-packages\pydub\utils.py", line 263, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
  File "c:\users\rishabh\appdata\local\programs\python\python37\Lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "c:\users\rishabh\appdata\local\programs\python\python37\Lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Rishabh\Desktop\audio\dejavu\dejavu\__init__.py", line 77, in fingerprint_directory
    song_name, hashes, file_hash = iterator.next()
  File "c:\users\rishabh\appdata\local\programs\python\python37\Lib\multiprocessing\pool.py", line 748, in next
    raise value
FileNotFoundError: [WinError 2] The system cannot find the file specified
Failed fingerprinting
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "c:\users\rishabh\appdata\local\programs\python\python37\Lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Rishabh\Desktop\audio\dejavu\dejavu\__init__.py", line 180, in _fingerprint_worker
    channels, Fs, file_hash = decoder.read(filename, limit)
  File "C:\Users\Rishabh\Desktop\audio\dejavu\dejavu\decoder.py", line 51, in read
    audiofile = AudioSegment.from_file(filename)
  File "C:\Users\Rishabh\Desktop\audio\venv\lib\site-packages\pydub\audio_segment.py", line 665, in from_file
    info = mediainfo_json(orig_file)
  File "C:\Users\Rishabh\Desktop\audio\venv\lib\site-packages\pydub\utils.py", line 263, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
  File "c:\users\rishabh\appdata\local\programs\python\python37\Lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "c:\users\rishabh\appdata\local\programs\python\python37\Lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Rishabh\Desktop\audio\dejavu\dejavu\__init__.py", line 77, in fingerprint_directory
    song_name, hashes, file_hash = iterator.next()
  File "c:\users\rishabh\appdata\local\programs\python\python37\Lib\multiprocessing\pool.py", line 748, in next
    raise value
FileNotFoundError: [WinError 2] The system cannot find the file specified
Failed fingerprinting
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "c:\users\rishabh\appdata\local\programs\python\python37\Lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Rishabh\Desktop\audio\dejavu\dejavu\__init__.py", line 180, in _fingerprint_worker
    channels, Fs, file_hash = decoder.read(filename, limit)
  File "C:\Users\Rishabh\Desktop\audio\dejavu\dejavu\decoder.py", line 51, in read
    audiofile = AudioSegment.from_file(filename)
  File "C:\Users\Rishabh\Desktop\audio\venv\lib\site-packages\pydub\audio_segment.py", line 665, in from_file
    info = mediainfo_json(orig_file)
  File "C:\Users\Rishabh\Desktop\audio\venv\lib\site-packages\pydub\utils.py", line 263, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
  File "c:\users\rishabh\appdata\local\programs\python\python37\Lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "c:\users\rishabh\appdata\local\programs\python\python37\Lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Rishabh\Desktop\audio\dejavu\dejavu\__init__.py", line 77, in fingerprint_directory
    song_name, hashes, file_hash = iterator.next()
  File "c:\users\rishabh\appdata\local\programs\python\python37\Lib\multiprocessing\pool.py", line 748, in next
    raise value
FileNotFoundError: [WinError 2] The system cannot find the file specified
Failed fingerprinting
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "c:\users\rishabh\appdata\local\programs\python\python37\Lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Rishabh\Desktop\audio\dejavu\dejavu\__init__.py", line 180, in _fingerprint_worker
    channels, Fs, file_hash = decoder.read(filename, limit)
  File "C:\Users\Rishabh\Desktop\audio\dejavu\dejavu\decoder.py", line 51, in read
    audiofile = AudioSegment.from_file(filename)
  File "C:\Users\Rishabh\Desktop\audio\venv\lib\site-packages\pydub\audio_segment.py", line 665, in from_file
    info = mediainfo_json(orig_file)
  File "C:\Users\Rishabh\Desktop\audio\venv\lib\site-packages\pydub\utils.py", line 263, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
  File "c:\users\rishabh\appdata\local\programs\python\python37\Lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "c:\users\rishabh\appdata\local\programs\python\python37\Lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Rishabh\Desktop\audio\dejavu\dejavu\__init__.py", line 77, in fingerprint_directory
    song_name, hashes, file_hash = iterator.next()
  File "c:\users\rishabh\appdata\local\programs\python\python37\Lib\multiprocessing\pool.py", line 748, in next
    raise value
FileNotFoundError: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "example.py", line 29, in <module>
    song = djv.recognize(FileRecognizer, "mp3/Sean-Fournier--Falling-For-You.mp3")
  File "C:\Users\Rishabh\Desktop\audio\dejavu\dejavu\__init__.py", line 167, in recognize
    return r.recognize(*options, **kwoptions)
  File "C:\Users\Rishabh\Desktop\audio\dejavu\dejavu\recognize.py", line 42, in recognize
    return self.recognize_file(filename)
  File "C:\Users\Rishabh\Desktop\audio\dejavu\dejavu\recognize.py", line 30, in recognize_file
    frames, self.Fs, file_hash = decoder.read(filename, self.dejavu.limit)
  File "C:\Users\Rishabh\Desktop\audio\dejavu\dejavu\decoder.py", line 51, in read
    audiofile = AudioSegment.from_file(filename)
  File "C:\Users\Rishabh\Desktop\audio\venv\lib\site-packages\pydub\audio_segment.py", line 665, in from_file
    info = mediainfo_json(orig_file)
  File "C:\Users\Rishabh\Desktop\audio\venv\lib\site-packages\pydub\utils.py", line 263, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
  File "c:\users\rishabh\appdata\local\programs\python\python37\Lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "c:\users\rishabh\appdata\local\programs\python\python37\Lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
