### ISSUE TITLE
installation issue for Mysqldb

### ISSUE THREAD

**Issue by pk97** [worldveil/dejavu#158]
while  executing the following commands on MacOS --
`sudo pip install MySQL-python`

i got following error:
` the directory '/Users/craterzone/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.

The directory '/Users/craterzone/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.

Collecting MYSQL-python

  Downloading https://files.pythonhosted.org/packages/a5/e9/51b544da85a36a68debe7a7091f068d802fc515a3a202652828c73453cad/MySQL-python-1.2.5.zip (108kB)

    100% |████████████████████████████████| 112kB 182kB/s 

    Complete output from command python setup.py egg_info:

    Traceback (most recent call last):

      File "<string>", line 1, in <module>

      File "/private/tmp/pip-install-MkVZcs/MYSQL-python/setup.py", line 17, in <module>

        metadata, options = get_config()

      File "setup_posix.py", line 53, in get_config

        libraries = [ dequote(i[2:]) for i in libs if i.startswith(compiler_flag("l")) ]

      File "setup_posix.py", line 8, in dequote

        if s[0] in "\"'" and s[0] == s[-1]:

    IndexError: string index out of range

    

    ----------------------------------------

Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-install-MkVZcs/MYSQL-python/
`
How should I proceed?

**Comment by pk97** [comment]
This error got removed , thanks to 
[Stackoverflow](https://stackoverflow.com/questions/10062002/mysqldb-for-python-2-7-ubuntu#)

So on running the command : 
`sudo pip install MySQL-python`
i got falling warning:

`first_v) pulkit@pulkit-Satellite-C55-A:~/first_v/dejavu$ sudo pip install MySQL-python
The directory '/home/pulkit/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/pulkit/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.`

`Requirement already satisfied: MySQL-python in /usr/local/lib/python2.7/dist-packages (1.2.5)`


So that means mysqldb is present
Unfortunately on following INSTALLATION.md i got following error:
import dejavu.database_sql

`  File "/home/pulkit/first_v/dejavu/dejavu/database_sql.py", line 5, in <module>
    import MySQLdb as mysql `


totally confused

**Comment by MadhavChoudhary** [comment]
What is the version of python that you are using? Please mention that. 
```
pip install mysqlclient
```
It should solve the problem
