### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by nils-fl** [worldveil/dejavu#169]
Hi,
in principle it seems to do something when I run `python example.py` but I get:

`Failed fingerprinting
Traceback (most recent call last):
  File "/home/ml/dejavu/dejavu/__init__.py", line 78, in fingerprint_directory
    song_name, hashes, file_hash = iterator.next()
  File "/usr/local/lib/python2.7/multiprocessing/pool.py", line 673, in next
    raise value
ValueError: No JSON object could be decoded
Failed fingerprinting
Traceback (most recent call last):
  File "/home/ml/dejavu/dejavu/__init__.py", line 78, in fingerprint_directory
    song_name, hashes, file_hash = iterator.next()
  File "/usr/local/lib/python2.7/multiprocessing/pool.py", line 673, in next
    raise value
ValueError: No JSON object could be decoded
Failed fingerprinting
Traceback (most recent call last):
  File "/home/ml/dejavu/dejavu/__init__.py", line 78, in fingerprint_directory
    song_name, hashes, file_hash = iterator.next()
  File "/usr/local/lib/python2.7/multiprocessing/pool.py", line 673, in next
    raise value
ValueError: No JSON object could be decoded
Failed fingerprinting
Traceback (most recent call last):
  File "/home/ml/dejavu/dejavu/__init__.py", line 78, in fingerprint_directory
    song_name, hashes, file_hash = iterator.next()
  File "/usr/local/lib/python2.7/multiprocessing/pool.py", line 673, in next
    raise value
ValueError: No JSON object could be decoded
Failed fingerprinting
Traceback (most recent call last):
  File "/home/ml/dejavu/dejavu/__init__.py", line 78, in fingerprint_directory
    song_name, hashes, file_hash = iterator.next()
  File "/usr/local/lib/python2.7/multiprocessing/pool.py", line 673, in next
    raise value
ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "example.py", line 23, in <module>
    song = djv.recognize(FileRecognizer, "mp3/Sean-Fournier--Falling-For-You.mp3")
  File "/home/ml/dejavu/dejavu/__init__.py", line 168, in recognize
    return r.recognize(*options, **kwoptions)
  File "/home/ml/dejavu/dejavu/recognize.py", line 41, in recognize
    return self.recognize_file(filename)
  File "/home/ml/dejavu/dejavu/recognize.py", line 29, in recognize_file
    frames, self.Fs, file_hash = decoder.read(filename, self.dejavu.limit)
  File "/home/ml/dejavu/dejavu/decoder.py", line 51, in read
    audiofile = AudioSegment.from_file(filename)
  File "/usr/local/lib/python2.7/site-packages/pydub/audio_segment.py", line 660, in from_file
    info = mediainfo_json(orig_file)
  File "/usr/local/lib/python2.7/site-packages/pydub/utils.py", line 267, in mediainfo_json
    info = json.loads(output)
  File "/usr/local/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded`

Does it mean that its not getting any features and the fingerprinting return is empty?

**Comment by Vaali** [comment]
Hi I too got the same error . Any ideas to solve this?
