### ISSUE TITLE
'va_us_top_40/wav/Mirrors - Justin Timberlake.wav'

### ISSUE THREAD

**Issue by grishabh282** [worldveil/dejavu#226]
Traceback (most recent call last):
  File "example.py", line 24, in <module>
    song = djv.recognize(FileRecognizer, "va_us_top_40/wav/Mirrors - Justin Timberlake.wav")
  File "C:\Users\Rishabh\Desktop\audio\dejavu\dejavu\__init__.py", line 168, in recognize
    return r.recognize(*options, **kwoptions)
  File "C:\Users\Rishabh\Desktop\audio\dejavu\dejavu\recognize.py", line 43, in recognize
    return self.recognize_file(filename)
  File "C:\Users\Rishabh\Desktop\audio\dejavu\dejavu\recognize.py", line 31, in recognize_file
    frames, self.Fs, file_hash = decoder.read(filename, self.dejavu.limit)
  File "C:\Users\Rishabh\Desktop\audio\dejavu\dejavu\decoder.py", line 58, in read
    audiofile = AudioSegment.from_file(filename)
  File "C:\Users\Rishabh\Desktop\audio\venv\lib\site-packages\pydub\audio_segment.py", line 610, in from_file
    file = _fd_or_path_or_tempfile(file, 'rb', tempfile=False)
  File "C:\Users\Rishabh\Desktop\audio\venv\lib\site-packages\pydub\utils.py", line 57, in _fd_or_path_or_tempfile
    fd = open(fd, mode=mode)
FileNotFoundError: [Errno 2] No such file or directory: 'va_us_top_40/wav/Mirrors - Justin Timberlake.wav'

**Comment by worldveil** [comment]
For obvious reasons, I didn't include copyrighted music in the repo
