### ISSUE TITLE
Failed fingerprinting

### ISSUE THREAD

**Issue by kpacn** [worldveil/dejavu#50]
Hello I have code that previously worked but now something change(I presume fingerprint directory with pool) and I can't make it work in fingerprint directory I receive following traceback error:

```
Failed fingerprinting
Traceback (most recent call last):
  File "/home/krasi/work/dj/src/dejavu/dejavu/__init__.py", line 74, in fingerprint_directory
    song_name, hashes = iterator.next()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 659, in next
    raise value
OSError: [Errno 2] No such file or directory
Failed fingerprinting
Traceback (most recent call last):
  File "/home/krasi/work/dj/src/dejavu/dejavu/__init__.py", line 74, in fingerprint_directory
    song_name, hashes = iterator.next()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 659, in next
    raise value
OSError: [Errno 2] No such file or directory
```

FIXED: Missing ffmpeg. In ubuntu 14 it also missing from the repositories.
solved with adding custom PPA:

sudo add-apt-repository ppa:mc3man/trusty-media
sudo apt-get update
sudo apt-get install ffmpeg gstreamer0.10-ffmpeg

**Comment by shemul** [comment]
Installed ffmpeg but still the issue exists to me .. what else to do ?
