### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by careuno** [worldveil/dejavu#96]
I'm getting this output when I try to run the example, I'm not an expert in python.

Failed fingerprinting
Traceback (most recent call last):
  File "/home/parallels/Documents/dejavu/dejavu/**init**.py", line 77, in fingerprint_directory
    song_name, hashes, file_hash = iterator.next()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 659, in next
    raise value
OSError: [Errno 2] No such file or directory
Failed fingerprinting
Traceback (most recent call last):
  File "/home/parallels/Documents/dejavu/dejavu/**init**.py", line 77, in fingerprint_directory
    song_name, hashes, file_hash = iterator.next()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 659, in next
    raise value
OSError: [Errno 2] No such file or directory
Failed fingerprinting
Traceback (most recent call last):
  File "/home/parallels/Documents/dejavu/dejavu/**init**.py", line 77, in fingerprint_directory
    song_name, hashes, file_hash = iterator.next()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 659, in next
    raise value
OSError: [Errno 2] No such file or directory
Failed fingerprinting
Traceback (most recent call last):
  File "/home/parallels/Documents/dejavu/dejavu/**init**.py", line 77, in fingerprint_directory
    song_name, hashes, file_hash = iterator.next()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 659, in next
    raise value
OSError: [Errno 2] No such file or directory
Failed fingerprinting
Traceback (most recent call last):
  File "/home/parallels/Documents/dejavu/dejavu/**init**.py", line 77, in fingerprint_directory
    song_name, hashes, file_hash = iterator.next()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 659, in next
    raise value
OSError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "example.py", line 21, in <module>
    song = djv.recognize(FileRecognizer, "mp3/Sean-Fournier--Falling-For-You.mp3")
  File "/home/parallels/Documents/dejavu/dejavu/**init**.py", line 167, in recognize
    return r.recognize(_options, *_kwoptions)
  File "/home/parallels/Documents/dejavu/dejavu/recognize.py", line 41, in recognize
    return self.recognize_file(filename)
  File "/home/parallels/Documents/dejavu/dejavu/recognize.py", line 29, in recognize_file
    frames, self.Fs, file_hash = decoder.read(filename, self.dejavu.limit)
  File "/home/parallels/Documents/dejavu/dejavu/decoder.py", line 51, in read
    audiofile = AudioSegment.from_file(filename)
  File "/usr/local/lib/python2.7/dist-packages/pydub/audio_segment.py", line 421, in from_file
    p = subprocess.Popen(conversion_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in **init**
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by gaborp** [comment]
I had the same issue. Ffmpeg reinstallation solved problems.

**Comment by even-zhang** [comment]
Is there anyone has tried to run the project on windows platform? I met the same problem, but the error is 
WindowsError: [Errno 2] No such file or directory

**Comment by doronfeldman** [comment]
@even-zhang make sure you have ffmpeg installed and added to path
https://github.com/jiaaro/pydub#installation

make sure that you can run `ffmpeg` in CMD
